# Simple Configuration - Matching ResNet Approach
# This config removes all complex features to match the successful ResNet implementation

model:
  name: "google/vit-base-patch16-224"
  pretrained: true
  num_classes: 5
  input_channels: 9
  dropout: 0.3
  use_simple_head: true  # Use SimpleMLP instead of AttentionMLPHead

# Data Configuration
data:
  data_root: "DL_Project_Processed_Data"
  train_split: "train"
  val_split: "val"
  test_split: "test"
  batch_size: 32  # Match ResNet
  num_workers: 0
  pin_memory: false

# Simple Augmentation - Match ResNet
augmentation:
  use_train_augmentation: true
  rotation_degrees: 5
  translate: [0.05, 0.05]
  horizontal_flip: true
  vertical_flip: false

# Simple Training Configuration
training:
  epochs: 100
  learning_rate: 0.001  # 1e-3, match ResNet
  weight_decay: 0.000001  # 1e-6, match ResNet
  optimizer: "adam"  # Simple Adam, not AdamW
  early_stopping: true
  patience: 10

# Simple Loss - BCE with pos_weight only
loss:
  type: "bce"  # Simple BCEWithLogitsLoss
  pos_weight_strategy: "log1p"  # Match ResNet's np.log1p

# Hardware Configuration
hardware:
  device: "mps"  # Use MPS on Mac
  seed: 2708  # Match ResNet seed for reproducibility

# Checkpoint Configuration
checkpoint:
  save_dir: "checkpoints/simple"
  save_best: true
  metric_for_best: "val_f1"
  mode: "max"


